//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easysave.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_GB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_GB() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("easysave.Ressources.en_GB", typeof(en_GB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chose the language you want to use:.
        /// </summary>
        internal static string language_ask_choice {
            get {
                return ResourceManager.GetString("language_ask_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current language.
        /// </summary>
        internal static string language_current {
            get {
                return ResourceManager.GetString("language_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Standard save.
        /// </summary>
        internal static string menu_basic_save {
            get {
                return ResourceManager.GetString("menu_basic_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error, impossible to load interface..
        /// </summary>
        internal static string menu_error_load {
            get {
                return ResourceManager.GetString("menu_error_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a save work.
        /// </summary>
        internal static string menu_new_save_work {
            get {
                return ResourceManager.GetString("menu_new_save_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string menu_settings {
            get {
                return ResourceManager.GetString("menu_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main menu.
        /// </summary>
        internal static string menu_title {
            get {
                return ResourceManager.GetString("menu_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save work liste.
        /// </summary>
        internal static string menu_work_list {
            get {
                return ResourceManager.GetString("menu_work_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change configuration file location (save slots).
        /// </summary>
        internal static string setting_choice_config_path {
            get {
                return ResourceManager.GetString("setting_choice_config_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change language.
        /// </summary>
        internal static string settings_choice_language {
            get {
                return ResourceManager.GetString("settings_choice_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter the name of the backup job (note that the name of the folder that will be created will automatically contain the date and time of the backup):.
        /// </summary>
        internal static string slotcreation_ask_name {
            get {
                return ResourceManager.GetString("slotcreation_ask_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a save type:.
        /// </summary>
        internal static string slotcreation_ask_save_type {
            get {
                return ResourceManager.GetString("slotcreation_ask_save_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter existing path to save:.
        /// </summary>
        internal static string slotcreation_ask_source_path {
            get {
                return ResourceManager.GetString("slotcreation_ask_source_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter an existing path to save to:.
        /// </summary>
        internal static string slotcreation_ask_target_path {
            get {
                return ResourceManager.GetString("slotcreation_ask_target_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total.
        /// </summary>
        internal static string slotcreation_choice_save_type_complete {
            get {
                return ResourceManager.GetString("slotcreation_choice_save_type_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential.
        /// </summary>
        internal static string slotcreation_choice_save_type_differential {
            get {
                return ResourceManager.GetString("slotcreation_choice_save_type_differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interaction with the save slot:.
        /// </summary>
        internal static string slotinteraction_ask_operation {
            get {
                return ResourceManager.GetString("slotinteraction_ask_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer cette sauvegarde.
        /// </summary>
        internal static string slotinteraction_choice_delete_save_work {
            get {
                return ResourceManager.GetString("slotinteraction_choice_delete_save_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete this backup.
        /// </summary>
        internal static string slotinteraction_choice_run_save_work {
            get {
                return ResourceManager.GetString("slotinteraction_choice_run_save_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a save slot to edit:.
        /// </summary>
        internal static string slotselection_ask_slot_to_edit {
            get {
                return ResourceManager.GetString("slotselection_ask_slot_to_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a valid save work:.
        /// </summary>
        internal static string slotselection_ask_slot_valid_number {
            get {
                return ResourceManager.GetString("slotselection_ask_slot_valid_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a number..
        /// </summary>
        internal static string slotselection_error_invalid_number {
            get {
                return ResourceManager.GetString("slotselection_error_invalid_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No save work slots found in files, back to main menu.
        /// </summary>
        internal static string slotselection_error_no_slot {
            get {
                return ResourceManager.GetString("slotselection_error_no_slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target:.
        /// </summary>
        internal static string slotselection_info_slot_cible {
            get {
                return ResourceManager.GetString("slotselection_info_slot_cible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source:.
        /// </summary>
        internal static string slotselection_info_slot_source {
            get {
                return ResourceManager.GetString("slotselection_info_slot_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type:.
        /// </summary>
        internal static string slotselection_info_slot_type {
            get {
                return ResourceManager.GetString("slotselection_info_slot_type", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter l'application.
        /// </summary>
        internal static string menu_exit
        {
            get
            {
                return ResourceManager.GetString("menu_exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go back to main menu.
        /// </summary>
        internal static string settings_choice_back
        {
            get
            {
                return ResourceManager.GetString("settings_choice_back", resourceCulture);
            }
        }
    }
}
