//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easysave.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr_FR() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("easysave.Ressources.fr_FR", typeof(fr_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;extension des fichiers de log a été changée avec succès !.
        /// </summary>
        internal static string config_extension_update {
            get {
                return ResourceManager.GetString("config_extension_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les fichiers ont bien été copiés !.
        /// </summary>
        internal static string copy_file {
            get {
                return ResourceManager.GetString("copy-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le travail de sauvegarde a bien été supprimé !.
        /// </summary>
        internal static string delete_work {
            get {
                return ResourceManager.GetString("delete-work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension actuelle.
        /// </summary>
        internal static string extension_current {
            get {
                return ResourceManager.GetString("extension_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le langage a bien été modifié !.
        /// </summary>
        internal static string langage_update {
            get {
                return ResourceManager.GetString("langage_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez la langue que vous souhaitez utiliser :.
        /// </summary>
        internal static string language_ask_choice {
            get {
                return ResourceManager.GetString("language_ask_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langage actuel.
        /// </summary>
        internal static string language_current {
            get {
                return ResourceManager.GetString("language_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur, impossible de charger l&apos;interface..
        /// </summary>
        internal static string menu_error_load {
            get {
                return ResourceManager.GetString("menu_error_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter l&apos;application.
        /// </summary>
        internal static string menu_exit {
            get {
                return ResourceManager.GetString("menu_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un travail de sauvegarde.
        /// </summary>
        internal static string menu_new_save_work {
            get {
                return ResourceManager.GetString("menu_new_save_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde séquentielles.
        /// </summary>
        internal static string menu_save_all {
            get {
                return ResourceManager.GetString("menu_save_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres.
        /// </summary>
        internal static string menu_settings {
            get {
                return ResourceManager.GetString("menu_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Menu principal.
        /// </summary>
        internal static string menu_title {
            get {
                return ResourceManager.GetString("menu_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des travaux de sauvegarde.
        /// </summary>
        internal static string menu_work_list {
            get {
                return ResourceManager.GetString("menu_work_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le travail de sauvegarde a bien été créé et enregistré !&quot;.
        /// </summary>
        internal static string save_work {
            get {
                return ResourceManager.GetString("save-work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez une extension pour les logs :.
        /// </summary>
        internal static string setting_ask_extension {
            get {
                return ResourceManager.GetString("setting_ask_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changer l&apos;extension des logs.
        /// </summary>
        internal static string setting_choice_change_extension {
            get {
                return ResourceManager.GetString("setting_choice_change_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changer l&apos;emplacement du fichier de configuration (slots de sauvegarde).
        /// </summary>
        internal static string setting_choice_config_path {
            get {
                return ResourceManager.GetString("setting_choice_config_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour au menu principal.
        /// </summary>
        internal static string settings_choice_back {
            get {
                return ResourceManager.GetString("settings_choice_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changer la langue.
        /// </summary>
        internal static string settings_choice_language {
            get {
                return ResourceManager.GetString("settings_choice_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir le nom du travail de sauvegarde (notez que le nom du dossier qui sera créé contiendra automatiquement la date et heure de la sauvegarde) : .
        /// </summary>
        internal static string slotcreation_ask_name {
            get {
                return ResourceManager.GetString("slotcreation_ask_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir un type de sauvegarde :.
        /// </summary>
        internal static string slotcreation_ask_save_type {
            get {
                return ResourceManager.GetString("slotcreation_ask_save_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir chemin d&apos;accès existant à sauvegarder : .
        /// </summary>
        internal static string slotcreation_ask_source_path {
            get {
                return ResourceManager.GetString("slotcreation_ask_source_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir un chemin d&apos;accès existant sur lequel sauvegarder :.
        /// </summary>
        internal static string slotcreation_ask_target_path {
            get {
                return ResourceManager.GetString("slotcreation_ask_target_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complet.
        /// </summary>
        internal static string slotcreation_choice_save_type_complete {
            get {
                return ResourceManager.GetString("slotcreation_choice_save_type_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differentiel.
        /// </summary>
        internal static string slotcreation_choice_save_type_differential {
            get {
                return ResourceManager.GetString("slotcreation_choice_save_type_differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interaction avec le slot de sauvegarde :.
        /// </summary>
        internal static string slotinteraction_ask_operation {
            get {
                return ResourceManager.GetString("slotinteraction_ask_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer cette sauvegarde.
        /// </summary>
        internal static string slotinteraction_choice_delete_save_work {
            get {
                return ResourceManager.GetString("slotinteraction_choice_delete_save_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lancer cette sauvegarde.
        /// </summary>
        internal static string slotinteraction_choice_run_save_work {
            get {
                return ResourceManager.GetString("slotinteraction_choice_run_save_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choissez un slot de sauvegarde à éditer :.
        /// </summary>
        internal static string slotselection_ask_slot_to_edit {
            get {
                return ResourceManager.GetString("slotselection_ask_slot_to_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez un travail de sauvegarde valable :.
        /// </summary>
        internal static string slotselection_ask_slot_valid_number {
            get {
                return ResourceManager.GetString("slotselection_ask_slot_valid_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir un nombre..
        /// </summary>
        internal static string slotselection_error_invalid_number {
            get {
                return ResourceManager.GetString("slotselection_error_invalid_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun slot de travail trouvé dans les sauvegardes, retour en arrière.
        /// </summary>
        internal static string slotselection_error_no_slot {
            get {
                return ResourceManager.GetString("slotselection_error_no_slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choissez un slot de sauvegarde à éditer :.
        /// </summary>
        internal static string slotselection_info_editing {
            get {
                return ResourceManager.GetString("slotselection-info-editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cible : .
        /// </summary>
        internal static string slotselection_info_slot_cible {
            get {
                return ResourceManager.GetString("slotselection_info_slot_cible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source : .
        /// </summary>
        internal static string slotselection_info_slot_source {
            get {
                return ResourceManager.GetString("slotselection_info_slot_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type : .
        /// </summary>
        internal static string slotselection_info_slot_type {
            get {
                return ResourceManager.GetString("slotselection_info_slot_type", resourceCulture);
            }
        }
    }
}
